load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "rossy_utils",
    srcs = [file for file in glob([
        "io/*.cpp", "math/*.cpp", "solvers/*.cpp", "thirdparty/goldfarb/*.cc"])], # "general/*.cpp", ,"math/*.cpp"
    hdrs = [file for file in glob([
        "io/*.hpp", "math/*.hpp", "math/*.h", "general/*.hpp", "solvers/*.hpp", "thirdparty/goldfarb/*.hh"])], # "general/*.hpp", ,"math/*.hpp"
    # strip_include_prefix = "src/rossy_utils",
    deps = [
        "@eigen", 
        "@highs",
        "@com_github_qpoases//:qpoases", #
        "@com_github_osqp_eigen//:osqp_eigen",
        "//rossy_utils/thirdparty/yaml:yamlwrapper", 
        "//rossy_utils/thirdparty/cdd:myCdd",
        "//:gen_config",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "robot_system",
    srcs = [file for file in glob([
        "robot_system/*.cpp"])], # "general/*.cpp", ,"math/*.cpp"
    hdrs = [file for file in glob([
        "robot_system/*.hpp"])], # "general/*.hpp", ,"math/*.hpp"
    # strip_include_prefix = "src/rossy_utils",
    deps = [
        "@eigen", 
        "@com_github_stack_of_tasks_pinocchio//:pinocchio", 
        "rossy_utils", 
    ],
    visibility = ["//visibility:public"],
)


# cc_library(
#     name = "simple_viewer",
#     srcs = [file for file in glob([
#         "simple_viewer/*.cpp"])], # "general/*.cpp", ,"math/*.cpp"
#     hdrs = [file for file in glob([
#         "simple_viewer/*.hpp"])], # "general/*.hpp", ,"math/*.hpp"
#     # strip_include_prefix = "src/rossy_utils",
#     deps = [
#         "@eigen", 
#         "@osg",
#     ],
#     visibility = ["//visibility:public"],
# )
